### PR TITLE
Use ExceptionDispatchInfo

### LINKED ISSUE #124: Consider usage of ExceptionDispatchInfo instead of BubbleExceptionContainer
Current implementation with `BubbleExceptionContainer` have issue of changing original stacktrace.

Consider following code. Semantically it's identical to current behavior - if exception is throw, store it to some field and throw it elsewhere.
```csharp
void ThrowSomeException() => throw new InvalidOperationException();

void StoreAndThrowExample()
{
    try
    {
        try
        {
            ThrowSomeException();
        }
        catch (Exception ex)
        {
            var storedEx = ex;
            throw ex;
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

Result of invoking `StoreAndThrowExample` is
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Program.<<Main>$>g__StoreAndThrowExample|0_2()
```

Notice that original source is not listed in stacktrace.

Now look at this method that uses `ExceptionDispatchInfo`:
```csharp
void ExceptionDispatchInfoExample()
{
    try
    {
        try
        {
            ThrowSomeException();
        }
        catch (Exception ex)
        {
            var exInfo = ExceptionDispatchInfo.Capture(ex);
            exInfo.Throw();
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```
which produces following stacktrace:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Program.<<Main>$>g__ThrowSomeException|0_0()
   at Program.<<Main>$>g__ExceptionDispatchInfoExample|0_1()
--- End of stack trace from previous location ---
   at Program.<<Main>$>g__ExceptionDispatchInfoExample|0_1()
```

This approach is used in async-await

### PR DESCRIPTION
**Pull request by jl0pd**
Fixes #124

### CODE REVIEW

File: CodingSeb.ExpressionEvaluator/ExpressionEvaluator.cs [hunk 1]
```diff
@@ -4692,7 +4690,14 @@ public partial class MethodsGroupEncaps
...
     {
-        public Exception Exception { get; set; }
+        public BubbleExceptionContainer(Exception exception)
+        {
+            _dispatchInfo = ExceptionDispatchInfo.Capture(exception);
+        }
+
+        private readonly ExceptionDispatchInfo _dispatchInfo;
+
+        public void Throw() => _dispatchInfo.Throw();
```
Comment (jl0pd) [inline CodingSeb.ExpressionEvaluator/ExpressionEvaluator.cs:4700]: `BubbleExceptionContainer` is kept to minimize source breaking changes. `Exception` property is removed, but it can be returned
